### ISSUE TITLE
Parsing error on XML document

### ISSUE THREAD

**Issue by LucaGallinari** [magespecialist/m1-MSP_DevTools#14]
Hi, i am trying to use some API but this error occurs while loading this URL: http://mysite.local/api/?wsdl

![schermata del 2016-10-07 09-58-59](https://cloud.githubusercontent.com/assets/5822554/19182689/ce5b669a-8c74-11e6-8f37-aac78aaad5c3.png)

**Comment by phoenix128** [comment]
Hello @LucaGallinari ,
can you please tell us what kind of Document type has been declared?

**Comment by LucaGallinari** [comment]
It's "text/xml":
![schermata del 2016-10-07 14-34-38](https://cloud.githubusercontent.com/assets/5822554/19190020/539251a4-8c9b-11e6-9f6f-fe256ced93af.png)

**Comment by phoenix128** [comment]
I know it is not a fix, but can you please switch the doctype header with a simple `<!DOCTYPE html>` for a test?

**Comment by LucaGallinari** [comment]
But that page is supposed to be an xml page without the DOCTYPE. Tomorrow i can try to put that line in the body of the response, but i don't get what's the point of that. I think that the module is adding the script where it shouldn't, or not?

**Comment by phoenix128** [comment]
Ah, OK, I'm sorry, I did not correctly undrestand your scenario.
DevTools are probably trying to add the tracking information to your XML structure.

As far as now they are projected to disable this behaviour while performing an AJAX call, we can add a further check on response mimetype.

**Comment by phoenix128** [comment]
@LucaGallinari , update to 0.1.13, we just fixed it.
