### ISSUE TITLE
Wrong comment type on autogenerated css files

### ISSUE THREAD

**Issue by vmasciotta** [magespecialist/m1-MSP_DevTools#15]
Hi,
if You try to use a theme that includes some kind of autogeneration css file, msp_devtools will adds a comment like `<!-- MSPDEVTOOLS[5b8f8de2572b0cfb4b7603e43be54496] -->` on css file too.
 
With this kind of wrong comment,  browsers like firefox and chrome will skip the first selector in the css file, causing weird behaviours.

I discovered it using Porto theme and generating the css after I've enabled msp_devtools. Of course I could solve the issue disabling devtoos, generate a new css and enabling devtools again but maybe a nice idea would be to include some kind of ext recognition or exclusion for css files generated automatically by magento.

**Comment by phoenix128** [comment]
Hi @vmasciotta ,
this is probably caused by some server-side generated CSS by Porto.

Can you please try if the following patch fixes your issue?

**app/code/community/MSP/DevToos/Model/Observer.php** (around line 30):

Replace:

```
    protected function _injectHtmlAttribute($html, $blockId)
    {
        if (!$html) {
            return $html;
        }

        $html = '<!-- MSPDEVTOOLS[' . $blockId . '] -->' . $html . '<!-- /MSPDEVTOOLS[' . $blockId . '] -->';

        return $html;
    }
```

With:

```
    protected function _injectHtmlAttribute($html, $blockId)
    {
        if (!$html || !Mage::helper('msp_devtools')->doNotAddJs()) {
            return $html;
        }

        $html = '<!-- MSPDEVTOOLS[' . $blockId . '] -->' . $html . '<!-- /MSPDEVTOOLS[' . $blockId . '] -->';

        return $html;
    }
```

**Comment by vmasciotta** [comment]
Hi and thanks for your answer,
sadly the fix you suggested doesn't solve the problem, indeed I don't get any DEVTOOL comment if I change that method.

**Comment by phoenix128** [comment]
Hello @vmasciotta ,
sorry, there was a mistake in the code.

Try switching the if line like this:

`if (!$html || Mage::helper('msp_devtools')->doNotAddJs()) {`

**Comment by phoenix128** [comment]
Did it fix?

**Comment by vmasciotta** [comment]
Hi, I'm sorry if I'm late.
Actually it doesn't work, I did notice the mistake and I tried the change by myself with same code You posted later but nothing,
Digging a bit more in the Porto css generation flow I understood why.

Actually Porto uses a .phtml barebone file as template for css generation and this .phtml file is loaded as a common (anonymous) block, like this:
`Mage::app()->getLayout()->createBlock("core/template")->setData('area', 'frontend')->setTemplate($str4)->toHtml();`

`$str4` contains the phtml file path.

Loaded and rendered like a normal block, devtools recognise it as a regular block adding it's own code.

Idk if it's possible to solve this specific problem, but with current devtools architecture I think not.

Thanks for your support and for this awesome extension!

**Comment by phoenix128** [comment]
That's a very bad practice! What do you think about adding a method to suspend devtools tagging?

Something like this:

```
Mage::helper('msp_devtools')->pause();
Mage::app()->getLayout()->createBlock("core/template")->setData('area', 'frontend')->setTemplate($str4)->toHtml();
Mage::helper('msp_devtools')->resume();
```

It is quite simple for us to create a `pause` and `resume` method for this kind of issues.

**Comment by vmasciotta** [comment]
That would be great, I think that You should write a doc page like "how to suspend tagging" somewhere just for this cases.

About Porto, that is a very common theme I can tell You what file to patch.

**Comment by phoenix128** [comment]
Yes please.

**Comment by vmasciotta** [comment]
Sure, here it is

`app/code/local/Smartwave/Porto/Model/Cssconfig/Generator.php`

line 36

**Comment by phoenix128** [comment]
Hello @vmasciotta ,
there is branch "vmasciotta-fix" with the proposed fix.

Can you please test it and see if it works?

https://github.com/magespecialist/m1-MSP_DevTools/tree/vmasciotta-fix

`Mage::helper('msp_devtools')->pause();`

and 

`Mage::helper('msp_devtools')->resume();`

have been implemented

**Comment by vmasciotta** [comment]
Ok, I just tested it and looks fine.
