### ISSUE TITLE
"Open in PhpStorm" button not showing up

### ISSUE THREAD

**Issue by LucaGallinari** [magespecialist/m1-MSP_DevTools#16]
Hi, as the title says it's a while (1/2weeks) that i can't use the "open in phpstorm" button. I remember that i updated phpstorm to 2016.3.2 and maybe they changed something in the Remote Call plugin.
Here some screenshots:
![schermata del 2017-03-04 14-08-44](https://cloud.githubusercontent.com/assets/5822554/23579496/e749d4b8-00ee-11e7-847b-49bacd0f53f3.png)
![schermata del 2017-03-04 13-37-50](https://cloud.githubusercontent.com/assets/5822554/23579495/e747ac38-00ee-11e7-8552-2b26caaf532e.png)
![schermata del 2017-03-04 13-35-03](https://cloud.githubusercontent.com/assets/5822554/23579494/e7470350-00ee-11e7-86d0-d02e31970263.png)

**Comment by phoenix128** [comment]
Hello @LucaGallinari , we made some modification in Chrome extension and M1 module on PhpStorm links handling.
You should try upgrading Magento module. Your Chrome extension has been probably automatically updated by your browser, while your M1 extension is not.

I'm pretty sure it will fix, but if it does not please tell us and we will fix it immediately.

**Comment by LucaGallinari** [comment]
I am at the latest version v0.1.13 for the module and v2.1 for the extension but it still not showing up. I even found out that under the tab Magento->Blocks in the Chrome console there are some "open in phpstorm" buttons (the ones with only the icon) and they are working.

**Comment by phoenix128** [comment]
It is probably an issue with the M1 extension. Let us check it.

**Comment by phoenix128** [comment]
Fixed in 0.1.15, please upgrade Magento 1 module.
