### ISSUE TITLE
Admin layout is broken

### ISSUE THREAD

**Issue by LucaGallinari** [magespecialist/m1-MSP_DevTools#17]
After updating to the latest version the admin layout broke as you can see in these screenshots (in the dashboard there is an additional empty left sidebar):
![schermata del 2017-03-08 10-49-43](https://cloud.githubusercontent.com/assets/5822554/23698872/773b1162-03ed-11e7-840c-5274dd8e97a7.png)
![schermata del 2017-03-08 10-48-25](https://cloud.githubusercontent.com/assets/5822554/23698873/773eac3c-03ed-11e7-836d-f855a92aa37d.png)
![schermata del 2017-03-08 10-48-07](https://cloud.githubusercontent.com/assets/5822554/23698874/77410978-03ed-11e7-81f2-9fc4b65e7082.png)

This happen in a clean project too.

**Comment by phoenix128** [comment]
Regression bug fixed in 0.1.16
