### ISSUE TITLE
Collections tab is always empty

### ISSUE THREAD

**Issue by fballiano** [magespecialist/m1-MSP_DevTools#19]
is there something I can to to debug it?

**Comment by phoenix128** [comment]
Hello @fballiano ,
we are sorry, but that feature is only available in the M2 module.
M1 module is no more a priority since the widespread of M2.

If you like to add it we will appreciate any kind of contribution.

**Comment by fballiano** [comment]
then (at least at the moment) maybe we can add the "This feature is only available on DevTools for Magento 2" message that's in some other tabs :-)

**Comment by phoenix128** [comment]
@fballiano I think you are 100% right about this :)

**Comment by phoenix128** [comment]
Fixed in Chrome devtools 3.3.3, wait for automatic update.
