### ISSUE TITLE
Observers

### ISSUE THREAD

**Issue by arioch1984** [magespecialist/m1-MSP_DevTools#3]
Hi!
First thanks for your great work!

Your module is really great!

This is not a real issue but a request, have you in mind to integrate Observer functionality to M1 module?

Thank's in advantage.

Best regards.

**Comment by phoenix128** [comment]
@arioch1984 sure! We are already working on it. It is missing because this module was created for Magento 2 and then we created the porting for Magento 1. So something is still missing :)

**Comment by arioch1984** [comment]
Hi @phoenix128! 
Many thanks for your quick reply and your really great job with this module :)

If you like I will close this request and stay tuned for updates (do you plan to publish a github page plus a mailing list for this module?)

Or if you prefer I could maintain this tread open until this feature is implemented and propose myself as a beta tester for you :)

**Comment by phoenix128** [comment]
Just stay tuned... we will release it today ;)

**Comment by arioch1984** [comment]
Yeah!
You are the best :)

**Comment by phoenix128** [comment]
So sorry, we had some delay due to other tasks, we were not able to publish it today. The feature is almost ready. We will release in the very next days.

**Comment by arioch1984** [comment]
Hi!
Don’t worry about that :)

I will stay tuned :)

-- 
Fabio Brunelli
www.fabiobrunelli.it

Il giorno 12 agosto 2016 @ 22:57:56, Riccardo (notifications@github.com) ha scritto:

So sorry, we had some delay due to other tasks, we were not able to publish it today. The feature is almost ready. We will release in the very next days.

**Comment by arioch1984** [comment]
Hi guys!
I am tuned again ;)

**Comment by phoenix128** [comment]
Hi @arioch1984, sorry for the delay. The new feature is available on v0.1.2 just published.
**NOTE:** It requires Chrome developer tool 1.6 (just released, it will be available in 60 minutes max on Chrome Store)

**Comment by arioch1984** [comment]
Hi @phoenix128!
Thank's a lot for the update! :)
Now I could use the tab Observers, but unfortunately in every page it say "No data available in table" and the list is empty.
I am using your great module on a vanilla Magento 1.9.2.4 fronted, have you excluded Magento default events from the list?

Thank's a lot anyway for your great work!!!

**Comment by phoenix128** [comment]
I am trying it with 1.9.2.3 but it should be almost the same.
Are you sure you upgraded both the Magento module and the Chrome extension?

**Comment by phoenix128** [comment]
@arioch1984 you are right, a Varien Profiler drop-in class was missing and this affected the Observers tab too.

We just uploaded 0.1.3 that should fix this issue.

Thank you for your help.

**Comment by arioch1984** [comment]
Hi @phoenix128 
Thank's for your quick reply, I think there is a typo error in modman file, because when I composer update it tell me:
[ErrorException]
  Source /var/www/linkspa/vendor/msp/devtools-m1/app/code/community/Varien/Profiler does not exist

Infant if you read the modman file you have:
app/code/community/Varien/Profiler app/code/community/Varien/Profiler
Instead I think you have to:
app/code/community/Varien/Profiler.php app/code/community/Varien/Profiler.php

I think .php is missing, am I right?

Thank's a lot and sorry for all this problems :)

**Comment by phoenix128** [comment]
Yes, correct. We fixed it, try it now.
Thank you for your help, we really appreciate your contribute to improve this module.

**Comment by arioch1984** [comment]
Thank's @phoenix128!
Now it works like a charm!

You are the best :)
