### ISSUE TITLE
Events break the category management page

### ISSUE THREAD

**Issue by nadiasala** [magespecialist/m1-MSP_DevTools#4]
Hi !
Events declared in the <global> section break the category management page.
Moving them under <frontend> section solve the problem.

We wait forward for new release !!
Thank you.
Nadia

**Comment by phoenix128** [comment]
Hi @nadiasala, we fixed it.
We managed to keep the backend support for M1 too.

Plase also upgrade Chrome DevTools to version 1.6 (will be available in 60 minutes max on CHrome WebStore).

Thank you for your help.

**Comment by nadiasala** [comment]
Hi @phoenix128 
thank you. I will test it as soon as possible.
