### ISSUE TITLE
Layout update for adminhtml

### ISSUE THREAD

**Issue by nadiasala** [magespecialist/m1-MSP_DevTools#5]
Hi,
I noticed that the file msp_devtools.xml, used for adminhtml_system_config_edit layout update is outside layout folder for adminhtml default theme.
I thought it was a mapping error in modman file but also in source folder the position seems wrong.

Nadia

**Comment by phoenix128** [comment]
Hi @nadiasala,
thank you for this bug report.

We fixed it in 0.1.5 already available on github and packagist.
