### ISSUE TITLE
Undefined index while re-indexing

### ISSUE THREAD

**Issue by LucaGallinari** [magespecialist/m1-MSP_DevTools#9]
If I try to reindex one or all indexes from magento admin, it will give me this error:
![screen](https://cloud.githubusercontent.com/assets/5822554/18349332/23fbe1e8-75d1-11e6-836d-acd807096234.png)

I am on a fresh installation of Magento 1.9.2.4 with only this module at the last version (0.1.9).

**Comment by phoenix128** [comment]
We are unable to reproduce on Magento 1.9.2.4, but is seems a side effect of issue #8.
Please try the following patch to `AbstractOspRegistry`:

Replace line #135:
`$this->registeredOps[$parentOpId]['proper_time'] -= $this->registeredOps[$opId]['time'];`

With:

```
if (isset($this->registeredOps[$parentOpId])) {
    $this->registeredOps[$parentOpId]['proper_time'] -= $this->registeredOps[$opId]['time'];
}
```

If it works we will add to our official release.
Thank you for your help.

**Comment by LucaGallinari** [comment]
Thank you! Now it works.
